### ISSUE TITLE
Kernel not starting, Insights for Portal

### ISSUE THREAD

**Issue by jnbaene** [Esri/insights-scripting-guide#7]
Hello there!,

I am trying to test scripting on ArcGIS Insights in the Enterprise version, but when I try to connect to the kernel it never starts, it keeps loading  and in the command prompt there is no answer from the gateway. Also it does not show any error.

I´ve already tested my conection using ArcGIS Insights Local and it works correctly, its only on the portal were I find this issue.
Attached you can see a screenshot of the Command Prompt when I try to start the kernel. From there it doesn´t do anything else.

Thanks for any help
![kernel](https://user-images.githubusercontent.com/39124538/68252975-c8f34500-fff4-11e9-9d2c-f0667eac0898.png)

**Comment by phpmaps** [comment]
@jnbaene looks like insights is unable to make the websocket connection.   Might you be using VPN to connect to your portal ?

**Comment by jnbaene** [comment]
@phpmaps I'm connected from work, we're not using a VPN to make any connection.

**Comment by phpmaps** [comment]
@jnbaene your screen shot is helpful, but want to confirm what I see.  

Did you open a web browser and load ```https:<machine.domain.com>:9999/api/kernelspecs``` or did that request come from Insights running in your Enterprise?  Insights will make that kernelspecs call to identify what kernels are available for use.

The kernelgateway needs to be accessible on the same network as ArcGIS Enterprise, otherwise you will face connectivity issues.

**Comment by jnbaene** [comment]
@phpmaps the request came from Insights running in my company Portal. 

When you mention that the kernel gateway needs to be accessible on the same network, it means that the Anaconda environment should be in a server comunicating with the server where the Enterprise is deployed? hence not my computer?

My Browser is Chrome

**Comment by phpmaps** [comment]
@jnbaene Yes, that is the case.  To take advantage of Insights scripting in ArcGIS Enterprise the Portal and Jupyter Kernel Gateway and your web browser all need to be networked together (aka on the same domain).  This is because all 3 components send and receive commands, messages and data.  

If for some reason one piece is not on the same network, scripting will not work and my suggestion would be to use Insights Desktop for Windows or Mac.  

Per your last message, it sounds like your Jupyter Gateway is located on a different network / domain....that won't work.   Let me know if networking might be the problem....  If it is the problem, I think we should improve the documentation, so the steps are clear and folks choose the working alternative which would Insights Desktop.

**Comment by jnbaene** [comment]
@phpmaps Ok perfect I understand what you mean. I am not really experienced in setting up networks, servers, ArcGIS Enterprise setup, etc., so I have another question, is there a way in which I can put my laptop on the same network of the Enterprise installation?

From your explanation it’s clear that the problem is that my Jupyter Gateway is installed on my laptop, so its unable to communicate with the Enterprise Installation.  Improving documentation will be very appreciated, because as it is today is not clear the differences of how the communication works between the Jupyter Gateway and the Insights Installation, and I know of clients having troubles with setting up scripting on Enterprise and this could be an issue.

**Comment by phpmaps** [comment]
@jnbaene -  In Windows it's pretty easy, https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/join-a-computer-to-a-domain on Mac this may be useful - https://www.pluralsight.com/blog/tutorials/join-mac-to-windows-domain

Usually an IT / Network Admin handles adding / removing machines to a domain.   Thanks for reaching out.

**Comment by jnbaene** [comment]
@phpmaps Thank you for the information! 
I was checking the documentation to connect my laptop to the domain where the Enterprise installation is deployed, but I've just learned that it is installed on an Azure Cloude Server, in this case it'll work in the same way? or there is aditional set up required ?

**Comment by phpmaps** [comment]
@jnbaene - Here are some options to consider.

1. Hosting both ArcGIS Enterprise and the Jupyter Kernal Gateway in Azure, then using an Azure security group to restrict IP access to these resources
2. Hosting ArcGIS Enterprise in Azure, and then deploying the Jupyter Kernal Gateway or Anaconda on the same machine / IP as the web browser or Insights Desktop

**Comment by applecool** [comment]
Closing this issue as there has been no further conversation. Please feel free to re-open if the issue still exists.
